### ISSUE TITLE
Injecting

### ISSUE THREAD

**Issue by 7Ciagas** [s-y-n-q/ccapi#2]
theres a issue with injecting with "CeleryInject.exe" when i inject with it, it says locating services, and closes roblox.
![image](https://github.com/user-attachments/assets/6ee0ac65-c7d3-4bfa-bf7c-efb67458f11d)

**Comment by 7Ciagas** [comment]
Locating instance*

**Comment by s-y-n-q** [comment]
I cant fix this, this has something to do with celery itself, not ccapi.

**Comment by 7Ciagas** [comment]
alright, i figured that out a few days ago
